repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0 # update with `pre-commit autoupdate`
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        files: ^(test|dlgr|demos)/|setup.py

  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
      - id: prettier-format
        name: Format JS, YAML, and CSS
        entry: "bash -c '(yarn prettier --config .prettierrc --write . ) || exit 1'"
        language: system
      - id: compile-js
        name: Update JS build
        entry: "bash -c '( yarn run build && git add dlgr/griduniverse/static/scripts/dist ) || exit 1'"
        language: system
        files: "\\.js$"
        pass_filenames: false
