# Config file for automatic testing at travis-ci.org

language: python
dist: trusty
sudo: required

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=style
  - python: 3.6
    env: TOXENV=docs

addons:
  chrome: stable
  postgresql: "9.4"
  apt:
    packages:
    - pandoc
    - enchant
    - redis-server
services:
  - redis-server

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000 &

install:
  - pip install --upgrade pip
  - pip install tox==3.1.2
  - pip install google-compute-engine
  - wget -N http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - createuser dallinger --createdb
  - createdb -O dallinger dallinger
  - createdb -O dallinger dallinger-import
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  global:
  - DATABASE_URL=postgresql://dallinger@localhost/dallinger

# command to run tests, e.g. python setup.py test
script:
  - tox
