# Config file for automatic testing at travis-ci.org

language: python
dist: trusty
sudo: false

python:
  - "2.7"

addons:
  postgresql: "9.4"
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
    - redis-server
services:
  - redis-server

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - python setup.py develop

before_script:
  - createdb dallinger -U postgres

env:
  global:
  - DATABASE_URL=postgresql://postgres@localhost/dallinger

# command to run tests, e.g. python setup.py test
script:
  - py.test
