# Config file for automatic testing at travis-ci.org

language: python
dist: trusty
sudo: required

python:
  - "2.7"

addons:
  chrome: stable
  postgresql: "9.4"
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
    - redis-server
services:
  - redis-server

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000 &

install: 
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install odo google-compute-engine
  - wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - createuser dallinger --createdb
  - createdb -O dallinger dallinger
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  global:
  - DATABASE_URL=postgresql://dallinger@localhost/dallinger

# command to run tests, e.g. python setup.py test
script:
  - py.test
