# Config file for automatic testing at travis-ci.org

language: python
dist: trusty
sudo: required

python:
  - "2.7"

addons:
  chrome: stable
  postgresql: "9.4"
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
    - redis-server
  sauce_connect:
    username: "Your Sauce Labs username"
  jwt:
    secure: "fOgiH5NXiwR/mhhNPi/wmLf883iLc0Bc987B9S0pkGucChzYWzxwqLZDu+t+Gp1k498t2Dcq8+QhSSBKhEiU21U5vBKZUEJQy+ikVbMbQtX8dvcN1b6bAveNwiFlnFPQOhMn/cXVFroi0Bh3GiBTnyL6G+7JOhO/jv1QNJYqBaP/N2gIKN0OeEqt5M3Z/EvUmwvGAKUYS2a2fUDSM2Mh3/00ZHeLIc6i8M+kTDwbeOd5oBTMB0iHtdgWlrMBHQjadm1KFi/eNNRvLBFkX6ygqctBpYtroX6gZk5+IniF+Bp2tL1v6/sSOeoyfqH59HsdTiLb9spI6/nwapVhNffInIqRdXXTQ/Mx0IFBcSbzDqJfOhSecCDOXXziuBkMXuBDb6/ijvWrmkjS/0c6bvFVgrkJCWbltyKd1rxm9kU1d/bBlZGgb/Raz9bEoSt2ClAZqk7DJva3B6Tqu6zEv1v+LD6a4N8O8ZZcVBOtd90R2coWPi07Jo/+FrphrCuF07UDRsN3QcekIAkg+EK9XZY8gW4An45IQDVoOdoZwaixSFEvDkmnawFCqky/Dmh6hMpdOWHjZGj6NSibIHp79FuZRVE5P8ADhiRQvFBPDLNpw7LrdgSAyMLPjj88Z51m2GkIi0scrDVZQHu+MdMwJtBb5tzCHJy38wcQhCMEkmMwdU8="

services:
  - redis-server

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000 &

install: 
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install odo google-compute-engine
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - createdb dallinger -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env:
  global:
  - DATABASE_URL=postgresql://postgres@localhost/dallinger

# command to run tests, e.g. python setup.py test
script:
  - py.test
